### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by Gogenator** [Whales/edigotia#1]
Here is the output after "make" command:
make 
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c city.cpp -o obj/city.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c color.cpp -o obj/color.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c cuss.cpp -o obj/cuss.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c files.cpp -o obj/files.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c game.cpp -o obj/game.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c geometry.cpp -o obj/geometry.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c globals.cpp -o obj/globals.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c glyph.cpp -o obj/glyph.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c interface.cpp -o obj/interface.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c main.cpp -o obj/main.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c map.cpp -o obj/map.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c resource.cpp -o obj/resource.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c rng.cpp -o obj/rng.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c species.cpp -o obj/species.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c stringfunc.cpp -o obj/stringfunc.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c wildlife.cpp -o obj/wildlife.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c window.cpp -o obj/window.o
g++ -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-char-subscripts -Wno-unused-parameter -g   -c world.cpp -o obj/world.o
world.cpp: In member function ‘void World::generate(Worldgen_spec)’:
world.cpp:432:23: error: ‘actual_spacing’ was not declared in this scope
   int spacing_start = actual_spacing / 2;
                       ^
world.cpp:449:23: error: ‘plate_post’ was not declared in this scope
   for (int i = 0; i < plate_post.size(); i++) {
                       ^
world.cpp:432:7: warning: unused variable ‘spacing_start’ [-Wunused-variable]
   int spacing_start = actual_spacing / 2;
       ^
make: *** [obj/world.o] Error 1

**Comment by SynedraAcus** [comment]
plate_post is probably a typo and should be plate_pos instead. The part about that array is just above the buggy line.
I don't get spacing_start and actual_spacing part at all, though. These two variables are not mentioned anywhere else in the code. I've tried removing this line altogether or putting smth else into spacing_start (e.g. x_spacing/2 or some random magic values). This lets the code compile, but the game segfaults upon world generation under either mod.

**Comment by Whales** [comment]
edigotia has been replaced at this point!  Please see SimpleEdi - it's much better!  https://github.com/Whales/SimpleEdi

I'll be removing this repo eventually, or at least replacing everything in it with the SimpleEdi files.
